spring:
  application:
    name: client-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}
  # Fallback if config server is down, to avoid "Failed to determine a suitable RDBC Connection URL" and similar errors.
  # This avoids the "Failed to determine a suitable RDBC Connection URL" error when config server is down, but it won't work if the config server is up and doesn't provide these properties.
  r2dbc:
    url: ${CLIENT_R2DBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
